---
title: "US Populated Places"
description: "Contribution to week 26 TidyTuesday: visualizing populated places in the United States"
---

# Historical Markers

```{r}

library('tidyverse')
library('camcorder')
library('ggrepel')
library('here')

here::i_am("us-populated-places.qmd")

```

Load data

```{r}

# Load place data

us_place_names <- 
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-27/us_place_names.csv'
  )

us_place_history <- 
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-27/us_place_history.csv'
  )

```

Data prep

```{r}

my_colors <- list(
  background = "#FFF1D6", 
  lines = "#481D24", 
  primary = "#C5283D", 
  secondary = "#255F85"
)

my_states <- c(
  "Maine", "New Hampshire", "Vermont", "Massachusetts", "Conneticut", "New York", "Delaware", "Pennsylvania"
)

is_colonial <- function(text) {
  digits <- str_extract_all(text, "\\b\\d+\\b")[[1]]
  return(any(as.numeric(digits) < 1800 & as.numeric(digits) > 1000))
}

us_geo_data <- 
  us_place_names %>%
  filter(
    state_name %in% my_states & 
      !is.na(prim_long_dec) &
      !is.na(prim_lat_dec)
  ) %>%
  inner_join(
    us_place_history, 
    by = "feature_id"
  ) %>%
  filter(
    !is.na(history)
  ) %>%
  mutate(
    is_colonial = purrr::map_lgl(history, is_colonial), 
    indian_name = stringr::str_detect(stringr::str_to_lower(history), "indian"), 
    state_abb = case_when(
        state_name == "Maine" ~ "ME", 
        state_name == "New Hampshire" ~ "NH", 
        state_name == "Vermont" ~ "VT", 
        state_name == "Massachusetts" ~ "MA", 
        state_name == "Conneticut" ~ "CT", 
        state_name == "New York" ~ "NY", 
        state_name == "Delaware" ~ "DE", 
        state_name == "Pennsylvania" ~ "PA", 
        TRUE ~ "X"
    )
  ) %>%
  filter(is_colonial) %>%
  usmap::usmap_transform(
    input_names = c("prim_long_dec", "prim_lat_dec")
  )

```

```{r}

gg_record(
  dir = 'C:/Users/Adam Bushman/Pictures/Camcorder', 
  device = 'png', 
  height = 9, 
  width = 16, 
  units = "cm", 
  dpi = 300
)

```

```{r}

usmap::plot_usmap(
  regions = "states", 
  include = my_states, 
  fill = my_colors$background, 
  color = my_colors$lines
) +
  geom_point(
    aes(x, y), 
    us_geo_data %>% filter(!indian_name), 
    color = my_colors$secondary, 
    alpha = 0.35, 
    size = 3, 
    show.legend = FALSE
  ) +
  geom_point(
    aes(x, y), 
    us_geo_data %>% filter(indian_name), 
    color = my_colors$primary, 
    alpha = 0.75, 
    size = 4, 
    show.legend = FALSE
  ) +
  geom_text_repel(
    aes(x, y, label = paste(feature_name, state_abb, sep = ", ")), 
    us_geo_data %>% filter(indian_name), 
    direction = "y", 
    box.padding = 0.5, 
    min.segment.length = 2, 
    max.overlaps = Inf, 
    nudge_x = 2
  ) +
  scale_color_identity() +
  scale_size_identity() +
  scale_alpha_identity()

```
